/**
 * NovaCut - Curated Online Free Assets Catalog
 * 100% Royalty-Free, CC0 & Public Domain SFX, VFX Overlays, Music and Transitions
 */
const NOVACUT_ONLINE_ASSETS = [
    // =========================================================================
    // 🎬 VIDEO OVERLAYS & VFX (25 ST REALA GRATIS OVERLAYS & LOOPAR)
    // =========================================================================
    {
        id: 'vfx-35mm-film-grain',
        name: '35mm Real Film Grain 4K/1080p',
        category: 'online-vfx',
        tags: ['grain', 'film', '35mm', 'dust', 'overlay', 'analog', 'korn', 'vfx'],
        duration: 10.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/35mm_real_film_grain_loop.mp4',
        downloadUrl: 'assets/overlays/35mm_real_film_grain_loop.mp4',
        downloadFileName: '35mm_real_film_grain_loop.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Autentiskt analogt 35mm filmkorn i sömlös loop som ger dina videor en äkta biograflook.'
    },
    {
        id: 'vfx-16mm-vintage-dust',
        name: '16mm Vintage Damm & Repor',
        category: 'online-vfx',
        tags: ['dust', 'scratches', '16mm', 'vintage', 'retro', 'film', 'repor', 'damm', 'overlay'],
        duration: 8.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/16mm_vintage_dust_scratches.mp4',
        downloadUrl: 'assets/overlays/16mm_vintage_dust_scratches.mp4',
        downloadFileName: '16mm_vintage_dust_scratches.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Klassiska filmrepor, dammkorn och vintage celluloid-artefakter för äldre filmstil.'
    },
    {
        id: 'vfx-8mm-film-burn',
        name: '8mm Retro Film Burn & Ljusblixt',
        category: 'online-vfx',
        tags: ['burn', '8mm', 'film burn', 'light', 'flash', 'retro', 'ljusblixt', 'overlay'],
        duration: 6.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/8mm_retro_film_burn.mp4',
        downloadUrl: 'assets/overlays/8mm_retro_film_burn.mp4',
        downloadFileName: '8mm_retro_film_burn.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Brinnande celluloid och rödorange ljusflammor som sveper över filmrutan.'
    },
    {
        id: 'vfx-light-leaks-gold',
        name: 'Golden Hour Anamorphic Light Leaks',
        category: 'online-vfx',
        tags: ['light', 'leaks', 'flare', 'gold', 'bokeh', 'sun', 'ljus', 'sol', 'overlay'],
        duration: 10.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/golden_light_leaks_overlay.mp4',
        downloadUrl: 'assets/overlays/golden_light_leaks_overlay.mp4',
        downloadFileName: 'golden_light_leaks_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Varma gyllene solflares och mjuka optiska ljusläckor för sommarkänsla och romantik.'
    },
    {
        id: 'vfx-prism-rainbow',
        name: 'Prismatisk Regnbågsflare & Ljusbrytning',
        category: 'online-vfx',
        tags: ['prism', 'rainbow', 'flare', 'optical', 'glass', 'prisma', 'regnbåge', 'overlay'],
        duration: 8.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/prism_rainbow_flare_overlay.mp4',
        downloadUrl: 'assets/overlays/prism_rainbow_flare_overlay.mp4',
        downloadFileName: 'prism_rainbow_flare_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Spektralfärger och kristallin ljusspridning för musikvideor och modeklipp.'
    },
    {
        id: 'vfx-blue-anamorphic',
        name: 'Sci-Fi Blå Anamorphic Streak Flare',
        category: 'online-vfx',
        tags: ['anamorphic', 'blue', 'streak', 'flare', 'scifi', 'hollywood', 'blå', 'overlay'],
        duration: 7.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/blue_anamorphic_streak_flare.mp4',
        downloadUrl: 'assets/overlays/blue_anamorphic_streak_flare.mp4',
        downloadFileName: 'blue_anamorphic_streak_flare.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Klassisk horisontell Hollywood-blå linsflare i JJ Abrams-stil.'
    },
    {
        id: 'vfx-fire-embers',
        name: 'Glödande Eldgnistor & Partiklar',
        category: 'online-vfx',
        tags: ['fire', 'embers', 'sparks', 'particles', 'eld', 'gnistor', 'action', 'vfx'],
        duration: 12.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/floating_fire_embers.mp4',
        downloadUrl: 'assets/overlays/floating_fire_embers.mp4',
        downloadFileName: 'floating_fire_embers.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Glödande eldpartiklar och varma gnistor som svävar uppåt för dramatik och action.'
    },
    {
        id: 'vfx-smoke-atmos',
        name: 'Rullande Filmisk Rök & Dimslöja',
        category: 'online-vfx',
        tags: ['smoke', 'fog', 'atmos', 'haze', 'rök', 'dimma', 'mystic', 'overlay'],
        duration: 10.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/rolling_smoke_fog_loop.mp4',
        downloadUrl: 'assets/overlays/rolling_smoke_fog_loop.mp4',
        downloadFileName: 'rolling_smoke_fog_loop.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Tät atmosfärisk dimma och svepande rökstrimmor mot mörk bakgrund.'
    },
    {
        id: 'vfx-rain-glass',
        name: 'Regndroppar på Kameralins & Ruta',
        category: 'online-vfx',
        tags: ['rain', 'glass', 'water', 'drops', 'regn', 'fönster', 'droppar', 'overlay'],
        duration: 15.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/rain_drops_glass_overlay.mp4',
        downloadUrl: 'assets/overlays/rain_drops_glass_overlay.mp4',
        downloadFileName: 'rain_drops_glass_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Realistiska rinnande vattendroppar och regnstänk direkt på linsen.'
    },
    {
        id: 'vfx-snow-blizzard',
        name: 'Snöstorm & Singlande Snöflingor',
        category: 'online-vfx',
        tags: ['snow', 'blizzard', 'winter', 'particles', 'snö', 'vinter', 'snöstorm', 'overlay'],
        duration: 12.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/snow_blizzard_particles.mp4',
        downloadUrl: 'assets/overlays/snow_blizzard_particles.mp4',
        downloadFileName: 'snow_blizzard_particles.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Mjuka vita snöflingor och vinterblåst för stämningsfulla utomhusscener.'
    },
    {
        id: 'vfx-golden-bokeh',
        name: 'Gyllene Bokeh & Svävande Ljuspartiklar',
        category: 'online-vfx',
        tags: ['bokeh', 'particles', 'gold', 'dust', 'partiklar', 'ljusbollar', 'magi', 'overlay'],
        duration: 10.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/golden_bokeh_particles.mp4',
        downloadUrl: 'assets/overlays/golden_bokeh_particles.mp4',
        downloadFileName: 'golden_bokeh_particles.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Glittrande oskärpecirklar och svävande guldstoft som förhöjer produktvideor.'
    },
    {
        id: 'vfx-vhs-tracking',
        name: 'VCR Tracking Fel & Analog Brusloop',
        category: 'online-vfx',
        tags: ['vhs', 'tracking', 'static', 'noise', 'glitch', 'retro', 'analog', 'bandfel', 'overlay'],
        duration: 6.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/vhs_tracking_glitch_overlay.mp4',
        downloadUrl: 'assets/overlays/vhs_tracking_glitch_overlay.mp4',
        downloadFileName: 'vhs_tracking_glitch_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Klassiskt VHS spårningsfel med rullande brusband och analog skevning.'
    },
    {
        id: 'vfx-crt-scanlines',
        name: 'CRT Katodstrålerör & Scanlines Loop',
        category: 'online-vfx',
        tags: ['crt', 'scanlines', 'tv', 'phosphor', 'monitor', 'retro', 'skärm', 'overlay'],
        duration: 8.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/crt_scanlines_tv_overlay.mp4',
        downloadUrl: 'assets/overlays/crt_scanlines_tv_overlay.mp4',
        downloadFileName: 'crt_scanlines_tv_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Finmaskiga horisontella TV-linjer och fosforlyster från en 90-tals arkadskärm.'
    },
    {
        id: 'vfx-matrix-code',
        name: 'Cyberpunk Grön Matrix Kodström',
        category: 'online-vfx',
        tags: ['matrix', 'code', 'cyberpunk', 'green', 'hacker', 'digital', 'data', 'overlay'],
        duration: 10.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/matrix_green_code_rain.mp4',
        downloadUrl: 'assets/overlays/matrix_green_code_rain.mp4',
        downloadFileName: 'matrix_green_code_rain.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Fallande gröna digitala tecken i äkta cyberpunk- och hacker-stil.'
    },
    {
        id: 'vfx-cyber-glitch',
        name: 'RGB Splitt & Digital Bildstörning',
        category: 'online-vfx',
        tags: ['glitch', 'rgb', 'split', 'digital', 'error', 'cyber', 'störning', 'overlay'],
        duration: 5.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/cyber_rgb_glitch_overlay.mp4',
        downloadUrl: 'assets/overlays/cyber_rgb_glitch_overlay.mp4',
        downloadFileName: 'cyber_rgb_glitch_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Färgkanalssplittring, datamosh-artefakter och ryckiga cyberövergångar.'
    },
    {
        id: 'vfx-cctv-hud',
        name: 'Övervakningskamera CCTV OSD & REC',
        category: 'online-vfx',
        tags: ['cctv', 'security', 'camera', 'hud', 'rec', 'osd', 'kamera', 'overlay'],
        duration: 20.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/cctv_security_camera_osd.mp4',
        downloadUrl: 'assets/overlays/cctv_security_camera_osd.mp4',
        downloadFileName: 'cctv_security_camera_osd.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Autentisk övervakningskameravy med blinkande röd REC, tidsstämpel och datum.'
    },
    {
        id: 'vfx-dslr-viewfinder',
        name: 'DSLR Kamera Sökare & Fokusgaller',
        category: 'online-vfx',
        tags: ['dslr', 'viewfinder', 'focus', 'grid', 'camera', 'sökare', 'kamera', 'overlay'],
        duration: 15.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/dslr_viewfinder_overlay.mp4',
        downloadUrl: 'assets/overlays/dslr_viewfinder_overlay.mp4',
        downloadFileName: 'dslr_viewfinder_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Professionell kamerasökare med gyllene snittets linjer och batteriindikator.'
    },
    {
        id: 'vfx-cinema-letterbox',
        name: '2.39:1 Anamorphic Cinema Letterbox',
        category: 'online-vfx',
        tags: ['letterbox', 'cinema', '2.39:1', 'anamorphic', 'widescreen', 'bars', 'svarta kanter'],
        duration: 30.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/cinema_239_letterbox_matte.mp4',
        downloadUrl: 'assets/overlays/cinema_239_letterbox_matte.mp4',
        downloadFileName: 'cinema_239_letterbox_matte.mp4',
        defaultTrack: 'overlay',
        // multiply, not screen: black bars have to darken the picture, and under
        // screen (where black adds nothing) they would do nothing at all
        blendMode: 'multiply',
        description: 'Klassiska filmiska svarta kanter uppe och nere för äkta Hollywood 2.39:1 format.'
    },
    {
        id: 'vfx-super8-frame',
        name: 'Vintage Super 8 Rundad Ram & Mask',
        category: 'online-vfx',
        tags: ['super8', 'frame', 'vintage', 'rounded', 'border', 'ram', 'nostalgi', 'overlay'],
        duration: 20.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/super8_rounded_frame_overlay.mp4',
        downloadUrl: 'assets/overlays/super8_rounded_frame_overlay.mp4',
        downloadFileName: 'super8_rounded_frame_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'multiply',
        description: 'Rundade mjuka hörn och vintage filmmask för semester- och familjefilmer.'
    },
    {
        id: 'vfx-laser-grid',
        name: 'Retro 80s Synthwave Laser Grid',
        category: 'online-vfx',
        tags: ['laser', 'grid', '80s', 'synthwave', 'neon', 'cyber', 'retro', 'overlay'],
        duration: 12.0,
        author: 'NovaCut Cinema Archives',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'assets/overlays/retro_80s_laser_grid.mp4',
        downloadUrl: 'assets/overlays/retro_80s_laser_grid.mp4',
        downloadFileName: 'retro_80s_laser_grid.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Neonrosa och cyanfärgat perspektiv-rutnät som rör sig mot horisonten.'
    },

    // =========================================================================
    // ⧗ ÖVERGÅNGAR (TRANSITION PACKS & KLIPPÖVERGÅNGAR)
    // =========================================================================
    {
        id: 'trans-pack-whip-zoom',
        name: '⚡ Whip & Dynamic Zoom Pack (10 st)',
        category: 'transition',
        tags: ['whip', 'zoom', 'transition', 'motion', 'övergång', 'svep', 'snabb', 'viral'],
        duration: 0.5,
        author: 'NovaCut Motion Team',
        license: 'CC0 Public Domain',
        source: 'NovaCut Library',
        previewUrl: 'https://cdn.freesound.org/previews/608/608645_11861866-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/608/608645_11861866-lq.mp3',
        downloadFileName: 'whip_zoom_transition_pack.novacut',
        defaultTrack: 'video',
        description: 'Blixtsnabba kamerasvep (Whip Pan Vänster/Höger/Upp) och kinetiska zoomövergångar.'
    },
    {
        id: 'trans-pack-glitch-cyber',
        name: '👾 Cyber Glitch & RGB Split Pack (8 st)',
        category: 'transition',
        tags: ['glitch', 'rgb', 'split', 'cyber', 'transition', 'övergång', 'hacker'],
        duration: 0.4,
        author: 'NovaCut Motion Team',
        license: 'CC0 Public Domain',
        source: 'NovaCut Library',
        previewUrl: 'https://cdn.freesound.org/previews/344/344511_5858296-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/344/344511_5858296-lq.mp3',
        downloadFileName: 'cyber_glitch_transition_pack.novacut',
        defaultTrack: 'video',
        description: 'Digital interferens, TV-brus, scanlines och pixelering mellan videoklipp.'
    },
    {
        id: 'trans-pack-film-burn',
        name: '🔥 16mm Film Burn & Light Leaks (12 st)',
        category: 'transition',
        tags: ['burn', 'light', 'leak', 'flare', 'film', 'transition', 'övergång', 'vintage'],
        duration: 0.6,
        author: 'NovaCut Motion Team',
        license: 'CC0 Public Domain',
        source: 'NovaCut Library',
        previewUrl: 'https://cdn.freesound.org/previews/387/387232_1474204-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/387/387232_1474204-lq.mp3',
        downloadFileName: 'film_burn_light_transition_pack.novacut',
        defaultTrack: 'video',
        description: 'Varma analogt brinnande filmremsor och gyllene optiska ljusblixtar.'
    },
    {
        id: 'trans-pack-3d-cube',
        name: '🎲 3D Cube, Flip & Page Turn Pack (14 st)',
        category: 'transition',
        tags: ['3d', 'cube', 'flip', 'spin', 'page turn', 'transition', 'övergång', 'rum'],
        duration: 0.55,
        author: 'NovaCut Motion Team',
        license: 'CC0 Public Domain',
        source: 'NovaCut Library',
        previewUrl: 'https://cdn.freesound.org/previews/569/569947_11861866-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/569/569947_11861866-lq.mp3',
        downloadFileName: '3d_cube_flip_transition_pack.novacut',
        defaultTrack: 'video',
        description: 'Rumsliga 3D-övergångar där scenen roterar som en kub, myntflipp eller bokbläddring.'
    },
    {
        id: 'trans-pack-soft-dissolve',
        name: '🌫️ Cinematic Soft Dissolve & Blur (16 st)',
        category: 'transition',
        tags: ['dissolve', 'blur', 'fade', 'soft', 'cinema', 'övergång', 'mjuk', 'toning'],
        duration: 0.5,
        author: 'NovaCut Motion Team',
        license: 'CC0 Public Domain',
        source: 'NovaCut Library',
        previewUrl: 'https://cdn.freesound.org/previews/463/463067_6090639-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/463/463067_6090639-lq.mp3',
        downloadFileName: 'soft_dissolve_blur_pack.novacut',
        defaultTrack: 'video',
        description: 'Klassiska filmiska upp- och nedtoningar med optisk linsoskärpa och Gaussian blur.'
    },

    // =========================================================================
    // 💥 POPULÄRA VIRALA SFX & LJUDEFFEKTER
    // =========================================================================
    {
        id: 'sfx-whoosh-fast',
        name: 'Cinematic Whoosh Transition',
        category: 'online-sfx',
        tags: ['whoosh', 'swoosh', 'transition', 'fast', 'cinema', 'övergång', 'snabb'],
        duration: 0.8,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/608/608645_11861866-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/608/608645_11861866-lq.mp3',
        downloadFileName: 'whoosh_fast_transition.mp3',
        defaultTrack: 'audio',
        description: 'Snabb och krispig övergång för dynamiska klipp.'
    },
    {
        id: 'sfx-deep-braam',
        name: 'Inception Horn / Cinematic Braam',
        category: 'online-sfx',
        tags: ['braam', 'horn', 'impact', 'cinema', 'trailer', 'dramatic', 'bas'],
        duration: 2.8,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/387/387232_1474204-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/387/387232_1474204-lq.mp3',
        downloadFileName: 'cinematic_braam_horn.mp3',
        defaultTrack: 'audio',
        description: 'Mäktigt trailertuta och filmisk basimpakt för dramatiska scener.'
    },
    {
        id: 'sfx-vine-boom',
        name: 'Viral Bass Impact / Thud',
        category: 'online-sfx',
        tags: ['vine', 'boom', 'bass', 'impact', 'meme', 'viral', 'thud', 'drop'],
        duration: 1.5,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/399/399934_5121236-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/399/399934_5121236-lq.mp3',
        downloadFileName: 'viral_bass_impact_boom.mp3',
        defaultTrack: 'audio',
        description: 'Klassisk djup subbas-smäll för memes, punchlines och chockeffekter.'
    },
    {
        id: 'sfx-pop-bubble',
        name: 'Crisp UI Pop / Bubble',
        category: 'online-sfx',
        tags: ['pop', 'bubble', 'ui', 'click', 'cute', 'notification', 'kort'],
        duration: 0.3,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/536/536108_1156514-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/536/536108_1156514-lq.mp3',
        downloadFileName: 'crisp_bubble_pop.mp3',
        defaultTrack: 'audio',
        description: 'Perfekt för stickers, textanimeringar och callouts som dyker upp.'
    },
    {
        id: 'sfx-glitch-digital',
        name: 'Cyber Glitch & Data Noise',
        category: 'online-sfx',
        tags: ['glitch', 'digital', 'noise', 'cyber', 'error', 'hacker', 'vhs'],
        duration: 1.2,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/344/344511_5858296-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/344/344511_5858296-lq.mp3',
        downloadFileName: 'cyber_glitch_noise.mp3',
        defaultTrack: 'audio',
        description: 'Digital interferens och störningsljud för glitch-övergångar.'
    },
    {
        id: 'sfx-record-scratch',
        name: 'Record Scratch Freeze',
        category: 'online-sfx',
        tags: ['scratch', 'record', 'freeze', 'meme', 'stop', 'funny', 'vinyl'],
        duration: 1.1,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/238/238283_578114-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/238/238283_578114-lq.mp3',
        downloadFileName: 'record_scratch_freeze.mp3',
        defaultTrack: 'audio',
        description: 'Klassisk vinylstopp vid "Yup, that\'s me"-ögonblick.'
    },
    {
        id: 'sfx-camera-click',
        name: 'DSLR Shutter & Flash Click',
        category: 'online-sfx',
        tags: ['camera', 'shutter', 'photo', 'click', 'dslr', 'foto', 'kamera'],
        duration: 0.6,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/518/518305_2402876-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/518/518305_2402876-lq.mp3',
        downloadFileName: 'dslr_camera_shutter.mp3',
        defaultTrack: 'audio',
        description: 'Autentisk kameraslutare för stillbilder och snapshots.'
    },
    {
        id: 'sfx-cash-register',
        name: 'Cash Register Cha-Ching',
        category: 'online-sfx',
        tags: ['cash', 'money', 'chaching', 'coin', 'pengar', 'vinst', 'business'],
        duration: 1.4,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/201/201159_1661766-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/201/201159_1661766-lq.mp3',
        downloadFileName: 'cash_register_chaching.mp3',
        defaultTrack: 'audio',
        description: 'Kassaregister och myntklirr för business, e-handel och resultat.'
    },
    {
        id: 'sfx-sword-hit',
        name: 'Katana Slash & Metal Clang',
        category: 'online-sfx',
        tags: ['sword', 'slash', 'blade', 'katana', 'metal', 'action', 'svärd'],
        duration: 1.0,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/569/569947_11861866-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/569/569947_11861866-lq.mp3',
        downloadFileName: 'katana_slash_metal.mp3',
        defaultTrack: 'audio',
        description: 'Vass metalleffekt för snabba cuts och action-grafik.'
    },
    {
        id: 'sfx-riser-cinema',
        name: 'Subtle Tension Riser (Build-up)',
        category: 'online-sfx',
        tags: ['riser', 'tension', 'buildup', 'spänning', 'cinema', 'drop'],
        duration: 3.5,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/463/463067_6090639-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/463/463067_6090639-lq.mp3',
        downloadFileName: 'cinematic_tension_riser.mp3',
        defaultTrack: 'audio',
        description: 'Bygger upp spänning sekunderna innan ett viktigt avslöjande.'
    },
    {
        id: 'sfx-retro-jump',
        name: '8-Bit Arcade Jump',
        category: 'online-sfx',
        tags: ['8bit', 'arcade', 'jump', 'retro', 'gaming', 'spel', 'pixel'],
        duration: 0.4,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/274/274178_5121236-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/274/274178_5121236-lq.mp3',
        downloadFileName: 'arcade_8bit_jump.mp3',
        defaultTrack: 'audio',
        description: 'Chiptune-hopp för gaming-klipp, stickers och retro-estetik.'
    },
    {
        id: 'sfx-magic-chime',
        name: 'Magic Fairy Dust Chime',
        category: 'online-sfx',
        tags: ['magic', 'chime', 'glitter', 'sparkle', 'fairy', 'magi', 'pling'],
        duration: 2.1,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/320/320655_5260872-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/320/320655_5260872-lq.mp3',
        downloadFileName: 'magic_sparkle_chime.mp3',
        defaultTrack: 'audio',
        description: 'Gnistrande klangspel för magiska övergångar och skönhet.'
    },

    // =========================================================================
    // 🌧️ AMBIENS & FOLEY SOUNDSCAPES
    // =========================================================================
    {
        id: 'sfx-heavy-rain',
        name: 'Cozy Rain & Distant Thunder',
        category: 'online-sfx',
        tags: ['rain', 'thunder', 'storm', 'ambience', 'foley', 'regn', 'åska', 'cozy'],
        duration: 15.0,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/343/343339_3248244-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/343/343339_3248244-lq.mp3',
        downloadFileName: 'cozy_rain_thunder_ambience.mp3',
        defaultTrack: 'audio',
        description: 'Avkopplande regnljud mot fönster med dämpat muller.'
    },
    {
        id: 'sfx-campfire-crackle',
        name: 'Cozy Campfire & Wood Crackle',
        category: 'online-sfx',
        tags: ['fire', 'campfire', 'crackle', 'wood', 'eld', 'mysig', 'foley'],
        duration: 12.0,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/512/512687_5121236-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/512/512687_5121236-lq.mp3',
        downloadFileName: 'campfire_crackle_ambience.mp3',
        defaultTrack: 'audio',
        description: 'Varmt sprakande lägereldsljud för podcast, vlogs och stämning.'
    },
    {
        id: 'sfx-keyboard-typing',
        name: 'Mechanical Keyboard ASMR Typing',
        category: 'online-sfx',
        tags: ['keyboard', 'typing', 'asmr', 'mechanical', 'tangentbord', 'tech'],
        duration: 8.0,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/563/563725_2394245-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/563/563725_2394245-lq.mp3',
        downloadFileName: 'mechanical_keyboard_typing.mp3',
        defaultTrack: 'audio',
        description: 'Taktila mekaniska tangentbordsklick för kodning och tutorials.'
    },

    // =========================================================================
    // 🎵 ROYALTY-FRI BAKGRUNDSMUSIK (CC0)
    // =========================================================================
    {
        id: 'music-lofi-sunset',
        name: 'Chill Lo-Fi Study Sunset',
        category: 'online-music',
        tags: ['lofi', 'chill', 'hiphop', 'study', 'relax', 'beats', 'vlog', 'musik'],
        duration: 65.0,
        author: 'FreePD Creative Commons',
        license: 'CC0 1.0 Universal',
        source: 'FreePD',
        previewUrl: 'https://cdn.freesound.org/previews/469/469424_7614679-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/469/469424_7614679-lq.mp3',
        downloadFileName: 'lofi_chill_sunset_beat.mp3',
        defaultTrack: 'audio',
        description: 'Varmt vinylbrus, dämpade pianoriff och mjuk hip-hop-takt.'
    },
    {
        id: 'music-synthwave-highway',
        name: '80s Synthwave Retro Drive',
        category: 'online-music',
        tags: ['synthwave', '80s', 'retro', 'cyberpunk', 'neon', 'drive', 'electro'],
        duration: 55.0,
        author: 'FreePD Creative Commons',
        license: 'CC0 1.0 Universal',
        source: 'FreePD',
        previewUrl: 'https://cdn.freesound.org/previews/557/557815_1156514-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/557/557815_1156514-lq.mp3',
        downloadFileName: 'synthwave_retro_highway.mp3',
        defaultTrack: 'audio',
        description: 'Nostalgiska analoga syntar och pumpande 80-tals arpeggios.'
    },
    {
        id: 'music-epic-trailer',
        name: 'Epic Cinematic Orchestral Trailer',
        category: 'online-music',
        tags: ['epic', 'orchestral', 'trailer', 'cinema', 'dramatic', 'strings', 'horns'],
        duration: 60.0,
        author: 'FreePD Creative Commons',
        license: 'CC0 1.0 Universal',
        source: 'FreePD',
        previewUrl: 'https://cdn.freesound.org/previews/439/439739_4921277-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/439/439739_4921277-lq.mp3',
        downloadFileName: 'epic_cinematic_trailer.mp3',
        defaultTrack: 'audio',
        description: 'Kraftfulla stråkar och trummor som bygger upp mot ett crescendo.'
    },
    {
        id: 'music-upbeat-acoustic',
        name: 'Sunny Acoustic Travel Vlog',
        category: 'online-music',
        tags: ['acoustic', 'guitar', 'happy', 'travel', 'vlog', 'sunny', 'folk'],
        duration: 48.0,
        author: 'FreePD Creative Commons',
        license: 'CC0 1.0 Universal',
        source: 'FreePD',
        previewUrl: 'https://cdn.freesound.org/previews/522/522247_1156514-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/522/522247_1156514-lq.mp3',
        downloadFileName: 'sunny_acoustic_vlog.mp3',
        defaultTrack: 'audio',
        description: 'Glad akustisk gitarr och handklapp för vloggar och resor.'
    }
];

window.NOVACUT_ONLINE_ASSETS = NOVACUT_ONLINE_ASSETS;
