/**
 * NovaCut - Curated Online Free Assets Catalog
 * 100% Royalty-Free, CC0 & Public Domain SFX, VFX Overlays and Music
 */
const NOVACUT_ONLINE_ASSETS = [
    // ==========================================
    // 💥 POPULÄRA VIRALA SFX & LJUDEFFEKTER
    // ==========================================
    {
        id: 'sfx-whoosh-fast',
        name: 'Cinematic Whoosh Transition',
        category: 'online-sfx',
        tags: ['whoosh', 'swoosh', 'transition', 'fast', 'cinema', 'övergång', 'snabb'],
        duration: 0.8,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/608/608645_11861866-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/608/608645_11861866-lq.mp3',
        downloadFileName: 'whoosh_fast_transition.mp3',
        defaultTrack: 'audio',
        description: 'Snabb och krispig övergång för dynamiska klipp.'
    },
    {
        id: 'sfx-deep-braam',
        name: 'Inception Horn / Cinematic Braam',
        category: 'online-sfx',
        tags: ['braam', 'horn', 'impact', 'cinema', 'trailer', 'dramatic', 'bas'],
        duration: 2.8,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/387/387232_1474204-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/387/387232_1474204-lq.mp3',
        downloadFileName: 'cinematic_braam_horn.mp3',
        defaultTrack: 'audio',
        description: 'Mäktigt trailertuta och filmisk basimpakt för dramatiska scener.'
    },
    {
        id: 'sfx-vine-boom',
        name: 'Viral Bass Impact / Thud',
        category: 'online-sfx',
        tags: ['vine', 'boom', 'bass', 'impact', 'meme', 'viral', 'thud', 'drop'],
        duration: 1.5,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/399/399934_5121236-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/399/399934_5121236-lq.mp3',
        downloadFileName: 'viral_bass_impact_boom.mp3',
        defaultTrack: 'audio',
        description: 'Klassisk djup subbas-smäll för memes, punchlines och chockeffekter.'
    },
    {
        id: 'sfx-pop-bubble',
        name: 'Crisp UI Pop / Bubble',
        category: 'online-sfx',
        tags: ['pop', 'bubble', 'ui', 'click', 'cute', 'notification', 'kort'],
        duration: 0.3,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/536/536108_1156514-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/536/536108_1156514-lq.mp3',
        downloadFileName: 'crisp_bubble_pop.mp3',
        defaultTrack: 'audio',
        description: 'Perfekt för stickers, textanimeringar och callouts som dyker upp.'
    },
    {
        id: 'sfx-glitch-digital',
        name: 'Cyber Glitch & Data Noise',
        category: 'online-sfx',
        tags: ['glitch', 'digital', 'noise', 'cyber', 'error', 'hacker', 'vhs'],
        duration: 1.2,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/344/344511_5858296-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/344/344511_5858296-lq.mp3',
        downloadFileName: 'cyber_glitch_noise.mp3',
        defaultTrack: 'audio',
        description: 'Digital interferens och störningsljud för glitch-övergångar.'
    },
    {
        id: 'sfx-record-scratch',
        name: 'Record Scratch Freeze',
        category: 'online-sfx',
        tags: ['scratch', 'record', 'freeze', 'meme', 'stop', 'funny', 'vinyl'],
        duration: 1.1,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/238/238283_578114-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/238/238283_578114-lq.mp3',
        downloadFileName: 'record_scratch_freeze.mp3',
        defaultTrack: 'audio',
        description: 'Klassisk vinylstopp vid "Yup, that\'s me"-ögonblick.'
    },
    {
        id: 'sfx-camera-click',
        name: 'DSLR Shutter & Flash Click',
        category: 'online-sfx',
        tags: ['camera', 'shutter', 'photo', 'click', 'dslr', 'foto', 'kamera'],
        duration: 0.6,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/518/518305_2402876-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/518/518305_2402876-lq.mp3',
        downloadFileName: 'dslr_camera_shutter.mp3',
        defaultTrack: 'audio',
        description: 'Autentisk kameraslutare för stillbilder och snapshots.'
    },
    {
        id: 'sfx-cash-register',
        name: 'Cash Register Cha-Ching',
        category: 'online-sfx',
        tags: ['cash', 'money', 'chaching', 'coin', 'pengar', 'vinst', 'business'],
        duration: 1.4,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/201/201159_1661766-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/201/201159_1661766-lq.mp3',
        downloadFileName: 'cash_register_chaching.mp3',
        defaultTrack: 'audio',
        description: 'Kassaregister och myntklirr för business, e-handel och resultat.'
    },
    {
        id: 'sfx-sword-hit',
        name: 'Katana Slash & Metal Clang',
        category: 'online-sfx',
        tags: ['sword', 'slash', 'blade', 'katana', 'metal', 'action', 'svärd'],
        duration: 1.0,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/569/569947_11861866-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/569/569947_11861866-lq.mp3',
        downloadFileName: 'katana_slash_metal.mp3',
        defaultTrack: 'audio',
        description: 'Vass metalleffekt för snabba cuts och action-grafik.'
    },
    {
        id: 'sfx-riser-cinema',
        name: 'Subtle Tension Riser (Build-up)',
        category: 'online-sfx',
        tags: ['riser', 'tension', 'buildup', 'spänning', 'cinema', 'drop'],
        duration: 3.5,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/463/463067_6090639-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/463/463067_6090639-lq.mp3',
        downloadFileName: 'cinematic_tension_riser.mp3',
        defaultTrack: 'audio',
        description: 'Bygger upp spänning sekunderna innan ett viktigt avslöjande.'
    },
    {
        id: 'sfx-retro-jump',
        name: '8-Bit Arcade Jump',
        category: 'online-sfx',
        tags: ['8bit', 'arcade', 'jump', 'retro', 'gaming', 'spel', 'pixel'],
        duration: 0.4,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/274/274178_5121236-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/274/274178_5121236-lq.mp3',
        downloadFileName: 'arcade_8bit_jump.mp3',
        defaultTrack: 'audio',
        description: 'Chiptune-hopp för gaming-klipp, stickers och retro-estetik.'
    },
    {
        id: 'sfx-magic-chime',
        name: 'Magic Fairy Dust Chime',
        category: 'online-sfx',
        tags: ['magic', 'chime', 'glitter', 'sparkle', 'fairy', 'magi', 'pling'],
        duration: 2.1,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/320/320655_5260872-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/320/320655_5260872-lq.mp3',
        downloadFileName: 'magic_sparkle_chime.mp3',
        defaultTrack: 'audio',
        description: 'Gnistrande klangspel för magiska övergångar och skönhet.'
    },

    // ==========================================
    // 🌧️ AMBIENS & FOLEY SOUNDSCAPES
    // ==========================================
    {
        id: 'sfx-heavy-rain',
        name: 'Cozy Rain & Distant Thunder',
        category: 'online-sfx',
        tags: ['rain', 'thunder', 'storm', 'ambience', 'foley', 'regn', 'åska', 'cozy'],
        duration: 15.0,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/343/343339_3248244-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/343/343339_3248244-lq.mp3',
        downloadFileName: 'cozy_rain_thunder_ambience.mp3',
        defaultTrack: 'audio',
        description: 'Avkopplande regnljud mot fönster med dämpat muller.'
    },
    {
        id: 'sfx-campfire-crackle',
        name: 'Cozy Campfire & Wood Crackle',
        category: 'online-sfx',
        tags: ['fire', 'campfire', 'crackle', 'wood', 'eld', 'mysig', 'foley'],
        duration: 12.0,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/512/512687_5121236-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/512/512687_5121236-lq.mp3',
        downloadFileName: 'campfire_crackle_ambience.mp3',
        defaultTrack: 'audio',
        description: 'Varmt sprakande lägereldsljud för podcast, vlogs och stämning.'
    },
    {
        id: 'sfx-keyboard-typing',
        name: 'Mechanical Keyboard ASMR Typing',
        category: 'online-sfx',
        tags: ['keyboard', 'typing', 'asmr', 'mechanical', 'tangentbord', 'tech'],
        duration: 8.0,
        author: 'Freesound CC0',
        license: 'CC0 Public Domain',
        source: 'Freesound',
        previewUrl: 'https://cdn.freesound.org/previews/563/563725_2394245-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/563/563725_2394245-lq.mp3',
        downloadFileName: 'mechanical_keyboard_typing.mp3',
        defaultTrack: 'audio',
        description: 'Taktila mekaniska tangentbordsklick för kodning och tutorials.'
    },

    // ==========================================
    // 🎬 VIDEO OVERLAYS & VFX (LOOPAR)
    // ==========================================
    {
        id: 'vfx-35mm-film-grain',
        name: '35mm Film Grain & Dust Loop',
        category: 'online-vfx',
        tags: ['grain', 'film', '35mm', 'dust', 'scratches', 'overlay', 'analog', 'korn'],
        duration: 8.0,
        author: 'NovaCut Open Cinema',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        downloadUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        downloadFileName: '35mm_film_grain_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Äkta analogt 35mm filmkorn som ger en filmisk biograftextur.'
    },
    {
        id: 'vfx-light-leaks-gold',
        name: 'Golden Light Leaks & Lens Flares',
        category: 'online-vfx',
        tags: ['light', 'leaks', 'flare', 'gold', 'bokeh', 'sun', 'ljus', 'sol'],
        duration: 10.0,
        author: 'NovaCut Open Cinema',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        downloadUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        downloadFileName: 'golden_light_leaks_overlay.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Varma gyllene solflares och organiska ljusreflexer.'
    },
    {
        id: 'vfx-fire-embers',
        name: 'Floating Fire Embers & Sparks',
        category: 'online-vfx',
        tags: ['fire', 'embers', 'sparks', 'particles', 'eld', 'gnistor', 'action'],
        duration: 12.0,
        author: 'NovaCut Open Cinema',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        downloadUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        downloadFileName: 'floating_fire_embers.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Glödande eldgnistor som stiger uppåt för action och filmiska scener.'
    },
    {
        id: 'vfx-smoke-atmos',
        name: 'Rolling Cinematic Fog & Smoke',
        category: 'online-vfx',
        tags: ['smoke', 'fog', 'atmos', 'haze', 'rök', 'dimma', 'mystic'],
        duration: 10.0,
        author: 'NovaCut Open Cinema',
        license: 'CC0 Public Domain',
        source: 'Internet Archive',
        previewUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        downloadUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        downloadFileName: 'rolling_smoke_fog_loop.mp4',
        defaultTrack: 'overlay',
        blendMode: 'screen',
        description: 'Tät rök och atmosfärisk dimma som sveper över bilden.'
    },

    // ==========================================
    // 🎵 ROYALTY-FRI BAKGRUNDSMUSIK (CC0)
    // ==========================================
    {
        id: 'music-lofi-sunset',
        name: 'Chill Lo-Fi Study Sunset',
        category: 'online-music',
        tags: ['lofi', 'chill', 'hiphop', 'study', 'relax', 'beats', 'vlog', 'musik'],
        duration: 65.0,
        author: 'FreePD Creative Commons',
        license: 'CC0 1.0 Universal',
        source: 'FreePD',
        previewUrl: 'https://cdn.freesound.org/previews/469/469424_7614679-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/469/469424_7614679-lq.mp3',
        downloadFileName: 'lofi_chill_sunset_beat.mp3',
        defaultTrack: 'audio',
        description: 'Varmt vinylbrus, dämpade pianoriff och mjuk hip-hop-takt.'
    },
    {
        id: 'music-synthwave-highway',
        name: '80s Synthwave Retro Drive',
        category: 'online-music',
        tags: ['synthwave', '80s', 'retro', 'cyberpunk', 'neon', 'drive', 'electro'],
        duration: 55.0,
        author: 'FreePD Creative Commons',
        license: 'CC0 1.0 Universal',
        source: 'FreePD',
        previewUrl: 'https://cdn.freesound.org/previews/557/557815_1156514-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/557/557815_1156514-lq.mp3',
        downloadFileName: 'synthwave_retro_highway.mp3',
        defaultTrack: 'audio',
        description: 'Nostalgiska analoga syntar och pumpande 80-tals arpeggios.'
    },
    {
        id: 'music-epic-trailer',
        name: 'Epic Cinematic Orchestral Trailer',
        category: 'online-music',
        tags: ['epic', 'orchestral', 'trailer', 'cinema', 'dramatic', 'strings', 'horns'],
        duration: 60.0,
        author: 'FreePD Creative Commons',
        license: 'CC0 1.0 Universal',
        source: 'FreePD',
        previewUrl: 'https://cdn.freesound.org/previews/439/439739_4921277-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/439/439739_4921277-lq.mp3',
        downloadFileName: 'epic_cinematic_trailer.mp3',
        defaultTrack: 'audio',
        description: 'Kraftfulla stråkar och trummor som bygger upp mot ett crescendo.'
    },
    {
        id: 'music-upbeat-acoustic',
        name: 'Sunny Acoustic Travel Vlog',
        category: 'online-music',
        tags: ['acoustic', 'guitar', 'happy', 'travel', 'vlog', 'sunny', 'folk'],
        duration: 48.0,
        author: 'FreePD Creative Commons',
        license: 'CC0 1.0 Universal',
        source: 'FreePD',
        previewUrl: 'https://cdn.freesound.org/previews/522/522247_1156514-lq.mp3',
        downloadUrl: 'https://cdn.freesound.org/previews/522/522247_1156514-lq.mp3',
        downloadFileName: 'sunny_acoustic_vlog.mp3',
        defaultTrack: 'audio',
        description: 'Glad akustisk gitarr och handklapp för vloggar och resor.'
    }
];

window.NOVACUT_ONLINE_ASSETS = NOVACUT_ONLINE_ASSETS;
